# Generated by Django 2.1.5 on 2019-02-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='image',
        ),
        migrations.AddField(
            model_name='diary',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
